pod 'BDGImagePicker', '~> 0.0.6'
pod 'BUKImagePickerController', '~> 0.1.10'

pod 'ELCImagePickerController', '~> 0.2.0'

#pod 'FLSImagePickerController', '~> 0.0.2'
#
#pod 'FMImagePickerController', '~> 0.1.6'
#
#pod 'FacebookImagePicker', '~> 2.0.8'
#
#pod 'GKImagePicker', '~> 0.0.1'
#
##pod 'GKImagePicker@arkuana', '~> 0.0.3'
##
##pod 'GKImagePicker@robseward', '~> 0.0.8'
#
#pod 'GMImagePicker', '~> 0.0.2'
#
#pod 'HDImagePicker', '~> 1.0'
#
#pod 'HGImagePicker', '~> 1.0.0'

pod 'HMImagePicker', '~> 1.0.3'

#pod 'HYPImagePicker', '~> 0.3'
#
#pod 'ImagePicker', '~> 1.1'
#
#pod 'ImagePickerSheet', '~> 0.0.9'
#
#pod 'ImagePickerSheetController', '~> 0.9.1'
#pod 'InstagramImagePicker', '~> 1.1.3'
#
pod 'JFImagePicker', '~> 1.0.0'
#
#pod 'JPImagePickerController', '~> 0.0.1'
#
#pod 'JPSImagePickerController', '~> 0.0.1'
#
#pod 'KCKeyboardImagePicker', '~> 0.4.2'
#
#pod 'KCKeyboardScrollingImagePicker', '~> 0.2.1'
#
#pod 'LCImagePickerController', '~> 0.1.7'
#
#pod 'LEMirroredImagePicker', '~> 0.1.0'
#
#pod 'LFImagePicker', '~> 0.3.8'
#
#pod 'MMSProfileImagePicker', '~> 1.0.1'
#
#pod 'NBUImagePicker', '~> 1.5.3'
#
#pod 'NFTImagePickerController', '~> 0.2.3'
pod 'NRImagePickerController', '~> 1.1.4'

pod 'Masonry', '~> 0.6.4'



pod 'AFNetworking', '~> 3.1.0'


